name: Build Check

on:
  pull_request:
    branches: [ main ]
    # Optional: You can also trigger on pushes to main if needed
    # push:
    #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Specify the Node.js versions you want to test against
        node-version: [20.x] 
        # You could add more versions like [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enable caching for npm dependencies

    - name: Install dependencies
      # Using 'npm ci' is generally faster and more reliable for CI
      # It installs dependencies exactly as defined in package-lock.json
      run: npm ci

    - name: Run build
      # This command executes the build script defined in your package.json
      run: npm run build 