name: Deploy Status Checker Lambda

on:
  push:
    branches: 
      - content
    paths:
      - 'src/penguindb/lambda_function/status_checker.py'
      - 'src/penguindb/utils/**'
      - 'docker_images/content_lambda_image.Dockerfile'
      - '.github/workflows/deploy_status_checker.yml'
    
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: content_lambda
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/amd64 --provenance=false -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker_images/content_lambda_image.Dockerfile --push .
          echo "::set-output name=image_uri::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy Lambda function
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: content_lambda
          IMAGE_TAG: latest
        run: |
          aws lambda update-function-code --function-name status_checker --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Retry Update Lambda Configuration
        run: |
          for i in {1..5}; do
            aws lambda update-function-configuration --function-name status_checker --environment "Variables={DYNAMODB_TABLE_NAME=content_data}" && break || sleep 15;
          done
      # - name: Get latest image tag
      #   id: get-image
      #   run: |
      #     aws ecr describe-images --repository-name penguindb-lambda --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' --output text
      #     echo "::set-output name=image_tag::$(aws ecr describe-images --repository-name penguindb-lambda --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' --output text)"

      # - name: Update Lambda function
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name status-checker-lambda \
      #       --image-uri ${{ secrets.ECR_REGISTRY }}/penguindb-lambda:${{ steps.get-image.outputs.image_tag }}

      # - name: Wait for update to complete
      #   run: |
      #     aws lambda wait function-updated --function-name status-checker-lambda 